<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AnnotationViewer</AssemblyName>
    <RootNamespace>MedVision.AnnotationViewer</RootNamespace>
    <ApplicationIcon>AnnotationViewer.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
